import { ArrowLeft, Check, ChevronRight, GitBranch, MoreHorizontal, Plus, ShieldCheck, Terminal, UserRound } from 'lucide-react';
import React from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { activity, attention, projects, queue } from './fixtures';
import { ActivityRow, ActorBadge, EmptyState, MetricCard, PageHeader, PrimaryActionButton, ProgressIndicator, ProjectOperationCard, SectionHeader, StatusBadge } from './components/ui';
import { RuntimeStatusPanel } from './components/RuntimeStatusPanel';
import type { Project } from './types';

function Placeholder({ title, description }: { title: string; description: string }) { return <><PageHeader title={title} description={description} action={<button className="secondary-button" type="button"><Plus size={15} />New view</button>} /><div className="placeholder-grid"><EmptyState title="UI surface ready" detail="Live project data becomes available in a later milestone." /><div className="placeholder-notes"><span className="eyebrow">M02 placeholder</span><h2>Designed for the next workflow step</h2><p>This view is intentionally static. It provides the navigation and states that future runtime services will populate.</p></div></div></>; }

export function CommandCenter() {
  const navigate = useNavigate(); const [notice, setNotice] = React.useState<string | null>(null);
  return <><PageHeader eyebrow="Portfolio overview" title="Command Center" description="A calm operational view of your development portfolio." action={<button className="secondary-button" type="button" onClick={() => setNotice('Refresh is available in a later milestone.')}><MoreHorizontal size={16} />Workspace actions</button>} />
    {notice ? <div className="safe-notice" role="status">{notice}<button type="button" onClick={() => setNotice(null)} aria-label="Dismiss message">Dismiss</button></div> : null}
    <section className="metric-grid" aria-label="Portfolio metrics"><MetricCard label="Total projects" value="05" detail="Across your workspace" /><MetricCard label="Active" value="03" detail="2 agents in progress" tone="blue" /><MetricCard label="Need attention" value="04" detail="Owner or external action" tone="warning" /><MetricCard label="Agent running" value="02" detail="Codex sessions" tone="running" /><MetricCard label="Audit required" value="01" detail="FMCG ERP" tone="audit" /><MetricCard label="Waiting external" value="01" detail="Scrubbots" tone="external" /></section><RuntimeStatusPanel />
    <div className="dashboard-grid"><section><SectionHeader title="Project operations" detail="Static M02 fixture data" action={<Link className="text-link" to="/projects">View all projects <ChevronRight size={15} /></Link>} /><div className="operations-grid">{projects.map(project => <ProjectOperationCard key={project.id} project={project} onAction={() => navigate(`/projects/${project.id}`)} />)}</div></section>
      <section className="attention-section"><SectionHeader title="Needs your attention" detail="Safe placeholders" /><div className="attention-list">{attention.map(item => <AttentionCard key={item.project + item.label} item={item} onAction={() => setNotice('Available in a later milestone.')} />)}</div></section></div>
    <div className="lower-grid"><section className="queue-section"><SectionHeader title="Active work queue" detail="4 items · updated moments ago" /><WorkQueue /></section><section className="brief-section"><SectionHeader title="AI Engineering Brief" detail="UI-only summary" /><div className="brief"><div className="brief-icon"><ShieldCheck size={18} /></div><p className="brief-summary">Your portfolio is moving steadily. One audit review and one external response are the current gates to watch.</p><div className="brief-stats"><span><b>4</b> projects updated</span><span><b>7</b> tasks completed</span><span><b>4</b> needs attention</span></div><div className="brief-next"><span>Recommended next action</span><strong>Review FMCG ERP audit findings</strong><PrimaryActionButton onClick={() => navigate('/audits')}>Open audit center</PrimaryActionButton></div></div></section></div>
    <section className="activity-section"><SectionHeader title="Recent activity" detail="Static event feed" action={<Link className="text-link" to="/activity">View activity <ChevronRight size={15} /></Link>} /><div className="activity-list">{activity.slice(0, 4).map(item => <ActivityRow key={item.id} {...item} />)}</div></section>
  </>;
}

function AttentionCard({ item, onAction }: { item: typeof attention[number]; onAction: () => void }) { return <article className="attention-card"><div className={`attention-icon attention-${item.icon}`}><ShieldCheck size={16} /></div><div><StatusBadge state={item.state} /><h3>{item.project}</h3><p>{item.detail}</p></div><button type="button" className="icon-button" onClick={onAction} aria-label={`Open ${item.project} placeholder`}><ChevronRight size={17} /></button></article>; }

function WorkQueue() { return <div className="queue-table" role="table" aria-label="Active work queue"><div className="queue-row queue-head" role="row"><span>Project</span><span>Task</span><span>Stage</span><span>Actor</span><span>State</span><span>Updated</span></div>{queue.map(item => <div className="queue-row" role="row" key={item.project}><strong>{item.project}</strong><span>{item.task}</span><span>{item.stage}</span><ActorBadge actor={item.actor} /><StatusBadge state={item.state} /><time>{item.updated}</time></div>)}</div>; }

export function Projects() { const navigate = useNavigate(); return <><PageHeader eyebrow="Workspace registry" title="Projects" description="A portfolio index prepared for future read-only project registration." action={<button className="primary-button" type="button"><Plus size={16} />Add project</button>} /><div className="filter-bar"><div className="filter-pills"><button className="filter-active" type="button">All projects <span>5</span></button><button type="button">Active <span>3</span></button><button type="button">Attention <span>2</span></button></div><span className="fixture-note">Fixture data · no repository connection</span></div><div className="projects-list">{projects.map(project => <ProjectOperationCard key={project.id} project={project} onAction={() => navigate(`/projects/${project.id}`)} />)}</div></>; }

export function ProjectCockpit() { const { id } = useParams(); const project = projects.find(item => item.id === id) ?? projects[0]; const [tab, setTab] = React.useState('Overview'); const tabs = ['Overview', 'Tasks', 'Workflow', 'Agents', 'Audit', 'Git', 'Tests', 'Activity', 'Files', 'Settings']; return <><Link className="back-link" to="/projects"><ArrowLeft size={15} />Back to projects</Link><div className="cockpit-header"><div className="project-mark project-mark-large">{project.code}</div><div><p className="eyebrow">Project cockpit · fixture</p><h1>{project.name}</h1><p>{project.description}</p></div><div className="cockpit-actions"><StatusBadge state={project.state} /><button className="icon-button" type="button" aria-label="Project options"><MoreHorizontal size={18} /></button></div></div><nav className="tabs" aria-label="Project cockpit tabs">{tabs.map(item => <button className={tab === item ? 'tab-active' : ''} type="button" key={item} onClick={() => setTab(item)}>{item}</button>)}</nav>{tab === 'Overview' ? <CockpitOverview project={project} /> : <div className="cockpit-placeholder"><EmptyState title={`${tab} view is staged`} detail="This tab is a polished placeholder. Runtime data arrives in later milestones." /></div>}</>; }

function CockpitOverview({ project }: { project: Project }) { return <><section className="cockpit-summary"><div><span className="eyebrow">Current task</span><h2>{project.task}</h2><p>Where we are: {project.phase}. Evidence and repository snapshots will populate this view when the runtime foundation arrives.</p><div className="cockpit-hero-actions"><PrimaryActionButton onClick={() => undefined}>View task detail</PrimaryActionButton><button className="secondary-button" type="button"><GitBranch size={15} />Open branch view</button></div></div><div className="cockpit-progress"><span>Milestone progress</span><strong>{project.progress}%</strong><ProgressIndicator value={project.progress} /><span className="health-label">Health <b className={`health-${project.health.toLowerCase()}`}>{project.health}</b></span></div></section><div className="cockpit-grid"><section className="panel"><SectionHeader title="Workflow pipeline" detail="Canonical state vocabulary" /><div className="pipeline">{['READY_FOR_IMPLEMENTATION', project.state, 'AUDIT_REQUIRED', 'VERIFY_REQUIRED', 'TASK_COMPLETE'].map((state, index) => <div className={`pipeline-step ${index < 2 ? 'pipeline-done' : ''}`} key={`${state}-${index}`}><span>{index < 1 ? <Check size={14} /> : index + 1}</span><strong>{state.replaceAll('_', ' ')}</strong>{index < 4 ? <ChevronRight size={14} /> : null}</div>)}</div></section><section className="panel"><SectionHeader title="Project metrics" /><div className="mini-metrics">{project.metrics.map(metric => <div key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong></div>)}</div></section></div><div className="cockpit-grid"><section className="panel"><SectionHeader title="Last completed action" /><div className="action-callout"><Check size={18} /><div><strong>{project.lastAction}</strong><span>Evidence will be attached by the local project registry.</span></div></div></section><section className="panel"><SectionHeader title="Next action" /><div className="action-callout action-next"><UserRound size={18} /><div><strong>{project.nextAction}</strong><span>Required actor: {project.actor}</span></div></div></section></div><section className="panel"><SectionHeader title="Recent activity" /><div className="activity-list">{activity.filter(item => item.project === project.name).map(item => <ActivityRow key={item.id} {...item} />)}<ActivityRow time={project.updated} project={project.name} actor={project.actor} event={project.lastAction} state={project.state} /></div></section></>; }

export function ActivityPage() { return <><PageHeader title="Activity" description="A chronological view of workspace events and evidence placeholders." /><section className="panel activity-page"><SectionHeader title="Workspace event feed" detail="5 static events" />{activity.map(item => <ActivityRow key={item.id} {...item} />)}</section></>; }
export function Tasks() { return <Placeholder title="Tasks" description="A normalized task workspace for future project sources." />; }
export function Agents() { return <Placeholder title="Agent Sessions" description="A safe surface for future Codex and Claude sessions." />; }
export function Audits() { return <Placeholder title="Audit Center" description="Independent review status across your projects." />; }
export function Settings() { return <Placeholder title="Settings" description="Workspace preferences and local-first policy controls." />; }
